name: image

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'

jobs:
  build:
    uses: edencehealth/workflows/.github/workflows/dockerimage.yml@v1
    with:
      container_name: sqlalchemy-omopcdm-modelgen
      push_readme: ./README.md
    secrets: inherit
